#!/bin/bash

# Prints SFO information of either a PS4 PKG or param.sfo file.
# Optional second argument is a key search string.
# Made with info from https://www.psdevwiki.com/ps4/Param.sfo

if [[ $1 == "" ]]; then
  echo "Usage: $0 <file> [<search string>]" >&2
  exit 1
fi

file=$1
search=${2,,}

getbytes() {
  xxd -u -p -s $(($1+pkgOffset)) -l "$2" "$file"
}

# Header
# https://www.psdevwiki.com/ps4/Param.sfo#Header_SFO
magic=$(getbytes 0x00 0x04)
if [[ $magic == 7F434E54 ]]; then # PKG file
  if pkgOffset=$(xxd "$file" | grep -m 1 "0050 5346"); then
    pkgOffset=0x${pkgOffset%%:*}
  else
    echo "Error: param.sfo magic not found inside PKG \"$1\"" >&2
    exit 1
  fi
elif [[ $magic == 00505346 ]]; then # param.sfo file
  pkgOffset=0
else
  echo "$1: Not a PKG neither a param.sfo file!" >&2
  exit 1
fi
header=$(getbytes 0x00 20)
keyTableOffset=${header:16:8}
keyTableOffset=0x${keyTableOffset:6:2}${keyTableOffset:4:2}${keyTableOffset:2:2}${keyTableOffset:0:2}
dataTableOffset=${header:24:8}
dataTableOffset=0x${dataTableOffset:6:2}${dataTableOffset:4:2}${dataTableOffset:2:2}${dataTableOffset:0:2}
indexTableEntries=${header:32:8}
indexTableEntries=$((0x${indexTableEntries:6:2}${indexTableEntries:4:2}${indexTableEntries:2:2}${indexTableEntries:0:2}))

# Get nullstring-delimited keys
# https://www.psdevwiki.com/ps4/Param.sfo#Key_table
i=0
while read -r -d $'\0' line; do
  key[$i]="$line"
  ((i++))
  [[ $i -gt $indexTableEntries ]] && break
done  < <(getbytes "$keyTableOffset" 5000 | xxd -r -p)

# Get full index table
# https://www.psdevwiki.com/ps4/Param.sfo#Index_table
indexTable=$(getbytes 0x14 $((0x10*indexTableEntries)))
indexTable=${indexTable//$'\n'} # xxd adds newlines which we must remove

# Get data
for ((i=0;i<indexTableEntries;i++)); do
  if [[ $search == "" ]]; then
    echo -n "${key[$i]}="
  elif [[ $search != "${key[$i],,}" ]]; then
    continue
  fi
  #keyOffset=${indexTable:$((i*32+0)):4}
  param_fmt=${indexTable:$((i*32+4)):4}
  paramLen=${indexTable:$((i*32+8)):8}
  paramLen=0x${paramLen:6:2}${paramLen:4:2}${paramLen:2:2}${paramLen:0:2}
  paramMaxLen=${indexTable:$((i*32+16)):8}
  paramMaxLen=0x${paramMaxLen:6:2}${paramMaxLen:4:2}${paramMaxLen:2:2}${paramMaxLen:0:2}
  dataOffset=${indexTable:$((i*32+24)):8}
  dataOffset=0x${dataOffset:6:2}${dataOffset:4:2}${dataOffset:2:2}${dataOffset:0:2}
  data=$(getbytes $((dataTableOffset+dataOffset)) "$paramLen")
  case "$param_fmt" in
    0400) # UTF-8 special mode string
      echo "[SPECIAL MODE STRING]"
      ;;
    0402) # UTF-8 string
      echo "${data%00}" | xxd -r -p
      echo
      ;;
    0404) # Integer
      data=0x${data:6:2}${data:4:2}${data:2:2}${data:0:2}
      echo "$((data))"
      ;;
    *) echo "[UNKNOWN DATA TYPE]"
  esac

  [[ $search == "${key[$i],,}" ]] && exit 0
done
